QUESTIOIN NO:1    Download a dataset from kaggle and upload it in jupyter
notebook or google colab. Perform any random operation on
the dataset.

In [ ]:
import pandas as pd
from google.colab import files

In [ ]:
data=files.upload()

Saving data.csv to data.csv


In [ ]:
import io
df=pd.read_csv(io.BytesIO(data['data.csv']))

In [ ]:
df.head()

eid         job   age experience promotion   salary
0   10       sales  34.0        yes       yes  10000.0
1   11     manager  23.0         no        no  20000.0
2   12         NaN  23.0        yes       yes  30000.0
3   13       sales  25.0        yes        no   5000.0
4   14  accounting  26.0         no       yes   5000.0

In [ ]:
df.head(2)

eid      job   age experience promotion   salary
0   10    sales  34.0        yes       yes  10000.0
1   11  manager  23.0         no        no  20000.0

QUESTION NO:2        Practice 10 python programs using numpy libraries

In [ ]:
import numpy as np
x=np.array([2,3,4,5])
print(x)

[2 3 4 5]


In [ ]:
x=np.array([2,3])
print(x)

[2 3]


In [ ]:
b=np.linspace(start=1,stop=5,num=10,endpoint=True,retstep=False)

In [ ]:
print(b)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
b=np.linspace(start=1,stop=5,num=10,endpoint=True,retstep=True)
print(b)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


In [ ]:
d=np.arange(1,10,3)

In [ ]:
print(d)

[1 4 7]


In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.rand(10)

array([0.72801761, 0.70940829, 0.16938561, 0.32934017, 0.83883307,
       0.68440869, 0.61641177, 0.01909999, 0.55610997, 0.62721525])

In [ ]:
# creating a list
x=range(1000)

In [ ]:
timeit sum(x)

100000 loops, best of 3: 13.9 µs per loop


In [ ]:
# creating numpy array
y=np.array(x)
print(y)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [ ]:
# reshape():recasts an array to new shape without changing it's data
grid=np.arange(start=1,stop=10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


QUESTION NO :3    Practice 10 python programs using pandas libraries.

In [ ]:
import pandas as pd
from google.colab import files

In [ ]:
cars_data=files.upload()

Saving Toyota.csv to Toyota (4).csv


In [ ]:
cars_data=pd.read_csv('Toyota.csv',index_col=0)

In [ ]:
cars_data

Price   Age     KM FuelType  ... Automatic    CC  Doors  Weight
0     13500  23.0  46986   Diesel  ...         0  2000  three    1165
1     13750  23.0  72937   Diesel  ...         0  2000      3    1165
2     13950  24.0  41711   Diesel  ...         0  2000      3    1165
3     14950  26.0  48000   Diesel  ...         0  2000      3    1165
4     13750  30.0  38500   Diesel  ...         0  2000      3    1170
...     ...   ...    ...      ...  ...       ...   ...    ...     ...
1431   7500   NaN  20544   Petrol  ...         0  1300      3    1025
1432  10845  72.0     ??   Petrol  ...         0  1300      3    1015
1433   8500   NaN  17016   Petrol  ...         0  1300      3    1015
1434   7250  70.0     ??      NaN  ...         0  1300      3    1015
1435   6950  76.0      1   Petrol  ...         0  1600      5    1114

[1436 rows x 10 columns]

In [ ]:
# 1) Shallow copy: >It is only creates a new variable that the reference of the original object
#                  >Any change made to a copy of object will reflect in the original 
samp=cars_data.copy(deep=False)  # or samp=cars_data

In [ ]:
samp

Price   Age     KM FuelType  ... Automatic    CC  Doors  Weight
0     13500  23.0  46986   Diesel  ...         0  2000  three    1165
1     13750  23.0  72937   Diesel  ...         0  2000      3    1165
2     13950  24.0  41711   Diesel  ...         0  2000      3    1165
3     14950  26.0  48000   Diesel  ...         0  2000      3    1165
4     13750  30.0  38500   Diesel  ...         0  2000      3    1170
...     ...   ...    ...      ...  ...       ...   ...    ...     ...
1431   7500   NaN  20544   Petrol  ...         0  1300      3    1025
1432  10845  72.0     ??   Petrol  ...         0  1300      3    1015
1433   8500   NaN  17016   Petrol  ...         0  1300      3    1015
1434   7250  70.0     ??      NaN  ...         0  1300      3    1015
1435   6950  76.0      1   Petrol  ...         0  1600      5    1114

[1436 rows x 10 columns]

In [ ]:
cars_data.index

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435],
           dtype='int64', length=1436)

In [ ]:
df = pd.DataFrame(cars_data)

In [ ]:
print(df)

      Price   Age     KM FuelType  ... Automatic    CC  Doors  Weight
0     13500  23.0  46986   Diesel  ...         0  2000  three    1165
1     13750  23.0  72937   Diesel  ...         0  2000      3    1165
2     13950  24.0  41711   Diesel  ...         0  2000      3    1165
3     14950  26.0  48000   Diesel  ...         0  2000      3    1165
4     13750  30.0  38500   Diesel  ...         0  2000      3    1170
...     ...   ...    ...      ...  ...       ...   ...    ...     ...
1431   7500   NaN  20544   Petrol  ...         0  1300      3    1025
1432  10845  72.0     ??   Petrol  ...         0  1300      3    1015
1433   8500   NaN  17016   Petrol  ...         0  1300      3    1015
1434   7250  70.0     ??      NaN  ...         0  1300      3    1015
1435   6950  76.0      1   Petrol  ...         0  1600      5    1114

[1436 rows x 10 columns]


In [ ]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df)

     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0


In [ ]:
cars_data.size

14360